from __future__ import annotations

from pathlib import Path

from .paths import context_path


POINTER = "Before starting work, read .agent-memory/claude-context.md for learned project-specific failure patterns."


def ensure_claude_pointer(root: Path) -> None:
    path = root / "CLAUDE.md"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if POINTER in text:
        return
    separator = "\n\n" if text and not text.endswith("\n\n") else ""
    path.write_text(f"{text}{separator}{POINTER}\n", encoding="utf-8")


def render_context(root: Path, db, config: dict, session_id: str | None = None) -> Path:
    path = context_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_context_content(db, config, session_id=session_id, record_injections=True)
    path.write_text(content, encoding="utf-8")
    return path


def render_context_content(db, config: dict, session_id: str | None = None, record_injections: bool = False) -> str:
    lessons = db.enabled_lessons(config["project_id"], config["max_lessons_injected"])

    lines = [
        "# Learned Failure Patterns",
        "",
        "Generated by memory-claude. Do not edit directly.",
        "",
        "When the user corrects you, or you discover a project-specific rule or fix,"
        " remember it in plain words for future sessions by running:",
        '`memory record-correction "<the rule, written clearly>"`',
        "",
    ]

    if not lessons:
        lines.extend(["No promoted lessons yet.", ""])

    for lesson in lessons:
        if record_injections:
            db.insert_injection(
                project_id=config["project_id"],
                session_id=session_id,
                lesson_id=lesson["id"],
                injection_type="before_session",
                reason="Selected for generated claude-context.md",
            )
        lines.extend(
            [
                f"## {lesson['title']}",
                "",
                lesson["lesson"],
                "",
                f"Confidence: {lesson['confidence']}",
                f"Last seen: {lesson['last_seen'][:10]}",
                f"Lesson ID: {lesson['id']}",
                "",
            ]
        )

    content = "\n".join(lines)
    max_chars = int(config["max_context_tokens"]) * 4
    if len(content) > max_chars:
        content = content[:max_chars].rstrip() + "\n"
    return content
